import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const baseUrl = 'http://localhost:3000'
  const examples = [
    <a href={`${baseUrl}/chessboard`}>Chessboard</a>,
    <a href={`${baseUrl}/counter`}>Counter</a>,
    <a href={`${baseUrl}/mouse-tracker`}>Mouse Tracker</a>,
    <a href={`${baseUrl}/lucky-numbers`}>Lucky Numbers</a>
  ]
  return (
    <div className={styles.container} style={{backgroundColor: '#fff'}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Projects</h2>
            <ul>
              {examples.map((link, id) => <li key={id}>{link}</li>)}
            </ul>
          </div>
        </div>
      </main>
    </div>
  )
}
